CREATE DATABASE DB_GENERATION_GAME_ONLINE;
USE DB_GENERATION_GAME_ONLINE; 

CREATE TABLE TB_CLASSES(
ID BIGINT AUTO_INCREMENT,
CLASSE VARCHAR(255) NOT NULL,
ARMA VARCHAR(255) NOT NULL,
PATENTE VARCHAR(255),
PRIMARY KEY(ID)
); 

CREATE TABLE TB_PERSONAGENS(
ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
HABILIDADE VARCHAR(255) NOT NULL,
ATAQUE BIGINT(5),
DEFESA BIGINT(5),
CLASSE_ID BIGINT,
PRIMARY KEY(ID),
FOREIGN KEY(CLASSE_ID) REFERENCES TB_CLASSES(ID)
);

INSERT INTO TB_CLASSES(CLASSE,ARMA,PATENTE)
	VALUES ("DUELISTA","VANDAL","DIAMANTE"); 
INSERT INTO TB_CLASSES(CLASSE,ARMA,PATENTE)
	VALUES ("INICIADOR","JUDGE","OURO"); 
INSERT INTO TB_CLASSES(CLASSE,ARMA,PATENTE)
	VALUES ("DUELISTA","SPECTRE","ASCENDENTE");
INSERT INTO TB_CLASSES(CLASSE,ARMA,PATENTE)
	VALUES ("CONTROLADOR","PHANTON","IMORTAL");
INSERT INTO TB_CLASSES(CLASSE,ARMA,PATENTE)
	VALUES ("SUPORTE","VANDAL","RADIANTE");
    
SELECT * FROM TB_CLASSES;

INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,ATAQUE,DEFESA,CLASSE_ID)
	VALUES ("REYNA","CEGAR O INIMIGO",5000,3000,1);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,ATAQUE,DEFESA,CLASSE_ID)
	VALUES ("SOVA","REVELA POSICAO DO INIMIGO",1500,3000,2);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,ATAQUE,DEFESA,CLASSE_ID)
	VALUES ("RAZE","JOGA GRANADA",4000,1000,3);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,ATAQUE,DEFESA,CLASSE_ID)
	VALUES ("OMEN","TELETRANSPORTA E SMOKA",1200,2000,4); 
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,ATAQUE,DEFESA,CLASSE_ID)
	VALUES ("SAGE","CURA OS ALIADOS",1000,6000,5);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,ATAQUE,DEFESA,CLASSE_ID)
	VALUES ("CYPHER","OBSERVA OS INIMIGOS COM UMA CAMERA",2000,3000,5);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,ATAQUE,DEFESA,CLASSE_ID)
	VALUES ("BREACH","CEGA OS INIMIGOS",4000,2000,6);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,ATAQUE,DEFESA,CLASSE_ID)
	VALUES ("KILLJOY","TORRETA ATIRADORA",1200,6000,7);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,ATAQUE,DEFESA,CLASSE_ID)
	VALUES ("CHAMBER","TELETRANSPORTA E TEM SNIPER",5000,2000,8);
    
SELECT * FROM TB_PERSONAGENS;

SELECT * FROM TB_PERSONAGENS WHERE ATAQUE > 2000;
SELECT * FROM TB_PERSONAGENS WHERE DEFESA >= 1000 AND DEFESA <= 2000; 

SELECT * FROM TB_PERSONAGENS WHERE NOME LIKE "%C%";

SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON
TB_CLASSES.CLASSE_ID = TB_CLASSES.ID; 

SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON
TB_CLASSES.CLASSE = "BANGA INIMIGO" AND TB_PERSONAGENS.CLASSE_ID = 6;

SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON
TB_CLASSES.CLASSE = "GRANADA" AND TB_PERSONAGENS.CLASSE_ID = 7;
